name: Deployment workflow
on: 
  push:
    branches: 
      - master
      - dev
      - stage

jobs:
  send-to-accelerate:
    runs-on: ubuntu-latest
    steps:
      - name: Push build data to Accelerate
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          
          ENV=${GITHUB_REF#refs/heads/}
          ENV="${ENV^^}"
          if [ $ENV = "MASTER" ]; then
            ENV="PROD"
          fi
          JSON_STRING=$( jq -n \
                  --arg version "${VERSION}" \
                  --arg id "b6010acd-0d4b-46c2-a59c-0659b7fc9d40" \
                  --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
                  --arg deploy_env "${ENV}" \
                  '{version: $version, application: { externalId: $id }, url: $url, environment: {name: $deploy_env}}' )
          echo $JSON_STRING
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug output
        run: |
          echo '${{ toJSON(github) }}'
