name: A workflow for my Hello World file
on: 
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment you are deploying to'
        required: true
        type: choice
        options: 
          - 'DEV'
          - 'STAGE'
          - 'PROD'
        default: 'DEV'

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  deploy:
    name: Deploy job
    runs-on: ubuntu-18.04
    steps:
      - name: test
        run: |
          echo "Deploying to: ${{ github.event.inputs.environment }}"
