name: A workflow for my Hello World file
on: 
  push:
    branches: 
      - master
      - dev

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  deploy:
    name: Deploy job
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-18.04
    steps:
      - name: test
        run: |
          echo "Deploying to: ${{ github.event.inputs.environment }}"
  send-to-accelerate:
    runs-on: ubuntu-latest
    steps:
      - name: Push build data to Accelerate
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ENV=${GITHUB_REF#refs/heads/}
          ENV="${ENV^^}"
          if [ $ENV = "MASTER" ]; then
            ENV="PROD"
          fi
          JSON_STRING=$( jq -n \
                  --arg version "${VERSION}" \
                  --arg id "b6010acd-0d4b-46c2-a59c-0659b7fc9d40" \
                  --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
                  --arg deploy_env "${ENV}" \
                  '{version: $version, application: { externalId: $id }, url: $url, environment: {name: $deploy_env}}' )
          echo $JSON_STRING
          
