name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: test
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -v -e "CREATE DATABASE test;"
