name: A workflow for my Hello World file
on: 
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment you are deploying to'
        required: true
        type: choice
        options: 
          - 'DEV'
          - 'STAGE'
          - 'PROD'
        default: 'DEV'

jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  deploy:
    name: Deploy job
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-18.04
    steps:
      - name: test
        run: |
          echo "Deploying to: ${{ github.event.inputs.environment }}"
  send-to-accelerate:
    runs-on: ubuntu-latest
    steps:
      - name: Push build data to Accelerate
        run: |-
          curl -k -X POST 'http://localhost/api/v1/builds/apiDriven' \
          -H 'Authorization: UserAccessKey ${{ secrets.ACCELERATE_KEY }}' \
          -H 'Content-Type: application/json' \
          -d '{
            "version": "${{ github.run_number }}"
            "application":{"externalId": "b6010acd-0d4b-46c2-a59c-0659b7fc9d40"},
            "url":"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
            "revision": "${{ github.sha }}"
            }'
