name: Tag workflow
on:
  push:
    branches: 
      - master
      - dev
      - stage
    tag:
      - 'v*'
      - '1.*'
jobs:
  get-details:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
      env: ${{ steps.info.outputs.env }}
    steps:
      - name: Get the branch and tag information
        id: info
        run: |
          if [[ ${{github.ref_type}} == 'tag' ]]; 
          then
            VERSION=${{github.ref_name}}
            ENV=${{github.event.base_ref}}
          elif [[ ${{github.ref_type}} == 'branch' ]]
            # What do we do for versions if this isn't a tag push
            VERSION=foobar
            ENV=${{github.ref_name}}
          fi
          ENV="${ENV^^}"
          if [ $ENV = "MASTER" ]; then
            ENV="PROD"
          fi
          echo '::set-output name=version::$VERSION'
          echo '::set-output name=env::$ENV'
  send-version-to-accelerate:
    runs-on: ubuntu-latest
    needs: get-details
    steps:
      - name: Push tagged version to Accelerate
        id: tag
        env:
          VERSION: ${{ needs.get-details.outputs.version }}
          ENV: ${{ needs.get-details.outputs.env }}
        run: |
          JSON_STRING=$( jq -n \
                  --arg version "$VERSION" \
                  --arg id "b6010acd-0d4b-46c2-a59c-0659b7fc9d40" \
                  --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
                  --arg sha "${{ github.sha }}" \
                  '{version: $version, application: { externalId: $id }, url: $url, revision: $sha}' )
          echo $JSON_STRING
  send-deployment-to-accelerate:
    runs-on: ubuntu-latest
    needs: [get-details, send-version-to-accelerate]
    steps:
      - name: Push deployment information to Accelerate
        run: |
          JSON_STRING=$( jq -n \
                  --arg version "${VERSION}" \
                  --arg id "b6010acd-0d4b-46c2-a59c-0659b7fc9d40" \
                  --arg url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
                  --arg deploy_env "${ENV}" \
                  '{version: $version, application: { externalId: $id }, url: $url, environment: {name: $deploy_env}}' )
          echo $JSON_STRING
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug output
        run: |
          echo '${{ toJSON(github) }}'
          